//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int id { get; set; }
        public string usuario { get; set; }
        public string contrasenia { get; set; }
        public Nullable<int> idState { get; set; }
        public Nullable<int> edad { get; set; }
    
        public virtual cstate cstate { get; set; }
    }
}
