//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id_usu { get; set; }
        public string user_usu { get; set; }
        public string password_usu { get; set; }
        public string email { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<int> id_cat { get; set; }
    
        public virtual cstate cstate { get; set; }
    }
}
